### ISSUE TITLE
Example Serial Communication Issue

### ISSUE THREAD

**Issue by gabepierng** [HaplyHaptics/Haply-API-cpp#1]
I am attempting to run the c++ example on my own laptop with the Developer board, and am having issues with the serial communication.

The example continues to trip the "Data not available" conditional when checking port->available() which in turn checks my_serial->available(). I noticed that the Serial objects *port and *my_serial (in WjwoodSerial) do not have the same address while debugging, so thought this may be the issue, but so far the serial buffer is always empty. 

The serial communication works fine with the processing IDE in the java setup

**Comment by ChristianFrisson** [comment]
Thanks for your report @gabepierng!

I would need more information so as to be able to help you:
- What board model and version are you using (see [versions](https://github.com/HaplyHaptics/Haply-API-cpp#versions))?
- What operating system are you using?

**Comment by gabepierng** [comment]
Board model: development kit board V0.3
Firmware: V0.4
Operating System: Mac OS 10.14.4 (Mojave)

Also in WjwoodSerial::open(), it identifies the correct port ('/dev/cu.usbmodem14101' in this case) and uses that to creating my_serial

**Comment by ChristianFrisson** [comment]
@gabepierng thanks, we need to update Haply-API-cpp to support firmware V0.4. See issue #2.

Please [watch this repository](https://help.github.com/en/articles/watching-and-unwatching-repositories#watching-a-single-repository) and/or [subscribe to both issues](https://help.github.com/en/articles/subscribing-to-and-unsubscribing-from-notifications) to receive updates.

**Comment by gabepierng** [comment]
If I downgraded the firmware to V0.2, should that fix the issue then? I uploaded the 0.2 firmware to the board, and it still gives the "data not available"

**Comment by ChristianFrisson** [comment]
Downgrading to V0.2 won't work, but to V0.1 should, since your board model supports all cited firmware versions.

**Comment by gabepierng** [comment]
I've tried all 3 versions, and none were able to receive any serial information.

**Comment by ChristianFrisson** [comment]
> Board model: development kit board V0.3
> Firmware: V0.4
> Operating System: Mac OS 10.14.4 (Mojave)
> 
> Also in WjwoodSerial::open(), it identifies the correct port ('/dev/cu.usbmodem14101' in this case) and uses that to creating my_serial

Note: the [Software Setup](https://github.com/HaplyHaptics/Getting-Started/tree/master/Software-Setup) lists `/dev/cu.usbmodem1411` as default port for macOS, I am assuming the added `0` in your quote is unintentional?

**Comment by ChristianFrisson** [comment]
> Board model: development kit board V0.3
> Firmware: V0.4
> Operating System: Mac OS 10.14.4 (Mojave)
> 
> Also in WjwoodSerial::open(), it identifies the correct port ('/dev/cu.usbmodem14101' in this case) and uses that to creating my_serial


I could successfully run Haply-API-cpp v0.1.0 (current) with Haply Modular Haptic Development Kit Firmware v0.1.0 for Haply Board v0.3 under macOS Sierra 10.12. I have not had the chance to test this setup under macOS Mojave 10.14 yet. I should have access to a macOS machine in the coming days.

**Comment by gabepierng** [comment]
No, the default port on this mac is 14101, with the 0. I've checked on another mac which had the same port, though I may try to set it up on a windows PC or older Mac and see if that changes anything

**Comment by ChristianFrisson** [comment]
Thanks for your patience and availability for testing!
I have switched from macOS 10.12 to Ubuntu Pop!_OS 18.10 during the development of Haply-API-cpp. So your older Mac sounds like the best bet to identity whether macOS versions affect serial communication with [wjwwood's serial](https://github.com/wjwwood/serial) library, or if the source of the problem lies somewhere else.

**Comment by ChristianFrisson** [comment]
Hi @gabepierng, @ehymowitz and I could successfully compile and run the main example with his laptop under his macOS Mojave 10.14.4, using both USB ports, one of them associated '/dev/cu.usbmodem14101' like yours. Have you tried with your older macbook?

**Comment by skianzad** [comment]
Hello, I have the same   "Data not available" problem and I have tried both on Windows and Mac on all the Arduino frameworks.

**Comment by ChristianFrisson** [comment]
Thanks for your report @skianzad !

I would need the following information so as to be able to help you:
- board model and version (printed on board)
- firmware version (folder from [Haply-Arduino-Firmware-Versions](https://github.com/HaplyHaptics/Haply-Arduino-Firmware-Versions))
- Haply-API-cpp version (0.1, 1.0, master?)

**Comment by skianzad** [comment]
- board model- Haply VO.3
- firmware version  V0.4
- Haply-API-cpp version (1.0 (master- I am not sure))

Thanks a lot.

**Comment by ChristianFrisson** [comment]
With firmware v0.4 and Haply-API-cpp v1.0, I have observed that the device needs to be re-plugged if examples are interrupted (and serial communication not closed properly). This does not happen with chai3d. Could you try to replug your device @skianzad ?

**Comment by skianzad** [comment]
I did so. Now I could run it on my Mac using Xcode but not on my Windows using visual studio!

**Comment by ChristianFrisson** [comment]
@skianzad Great that it worked on Mac. 

I opened related issue: Properly close serial communication on examples exit #3.

On Windows:
- What COM port is the device associated with? 
- Is it the same COM port that gets opened by the example?
- Are you generating a Visual Studio project using CMake?

**Comment by skianzad** [comment]
- COM3, Can you please tell me where I have to change the COM port to the designated port on my computer? Currently, I am only changing the one on the main cpp.  but I have seen one other on the wjwwoodSerial.cpp which is  port_name_match = "COM"; and I am not sure if I have to change it or not.

- I am generating it using CMake.  
@ChristianFrisson

**Comment by ChristianFrisson** [comment]
@skianzad Please try `COM3` instead of `COM10` here: https://github.com/HaplyHaptics/Haply-API-cpp/blob/967c1908ef86e9b6426ae50e63b88e7db72e0440/example/main.cpp#L80
Good to know that you are generating your Visual Studio project with CMake instead of from scratch.

**Comment by ChristianFrisson** [comment]
@gabepierng and @skianzad any updates from your side?

**Comment by skianzad** [comment]
Hey @ChristianFrisson , I stopped working on the visual studio on windows. Now I am using my MAC version which is working fine.

**Comment by gabepierng** [comment]
@ChristianFrisson sorry for the delay. Yup, once you released the v0.4 compatible update, was able to get the serial comm running on my Mac. Thanks!

**Comment by ChristianFrisson** [comment]
Good to know it is working for both of you @gabepierng and @skianzad on macOS. Closing the issue!
